# Generated by Django 5.0.6 on 2024-07-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others'), ('prefer not to say', 'Prefer not to say')], default='prefer not to say', max_length=100, null=True),
        ),
    ]
