# Generated by Django 5.0.6 on 2024-07-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalGuides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('phonenumber', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('guideplace', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('amountcharge', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
