# Generated by Django 5.0.6 on 2024-07-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_localguides'),
    ]

    operations = [
        migrations.AddField(
            model_name='localguides',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='local_guides/'),
        ),
    ]
