# Generated by Django 5.2.3 on 2025-06-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_image', models.ImageField(upload_to='event_images/')),
                ('event_name', models.CharField(max_length=200)),
                ('event_date_from', models.DateField()),
                ('event_date_to', models.DateField()),
                ('event_place', models.CharField(max_length=200)),
                ('event_time_from', models.TimeField()),
                ('event_time_to', models.TimeField()),
                ('event_website_link', models.URLField(blank=True, null=True)),
                ('about_event', models.TextField()),
            ],
        ),
    ]
