# Generated by Django 5.0.6 on 2024-07-12 04:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplan',
            name='members',
            field=models.ManyToManyField(related_name='accepted_travel_plans', to=settings.AUTH_USER_MODEL),
        ),
    ]
