# Generated by Django 5.0.6 on 2024-07-15 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tripmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
