# Generated by Django 5.0.6 on 2024-07-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplan',
            name='waiting_place',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
