# Generated by Django 5.0.6 on 2024-07-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_travelplan_waiting_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplan',
            name='group_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
